- type: antag
  id: DamnedCorsair
  name: roles-antag-damned-corsair-name
  antagonist: true
  setPreference: false
  objective: roles-antag-damned-corsair-objective

# Damned Corsair Starting Gear
- type: startingGear
  id: DamnedCorsairGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadHatPirate
    eyes: ClothingEyesSpectralEyepatch
    outerClothing: ClothingOuterCoatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    ears: ClothingHeadsetCommand
    belt: ClothingBeltUtility
