- type: antag
  id: SpectralPirate
  name: roles-antag-spectral-pirate-name
  antagonist: true
  setPreference: false
  objective: roles-antag-spectral-pirate-objective

# Spectral Pirate Starting Gear
- type: startingGear
  id: SpectralPirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadHatPirate
    eyes: ClothingEyesSpectralEyepatch
    outerClothing: ClothingOuterCoatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    ears: ClothingHeadsetCommand
    belt: ClothingBeltUtility
